#!/usr/bin/env bash
# Bash Script Utilities (or functions)
# Author: Ryan Lakner
# Created: 06-10-2025


black="\033[30m"
red="\033[31m"
green="\033[32m"
yellow="\033[33m"
blue="\033[34m"
purple="\033[35m"
cyan="\033[36m"
white="\033[37m"
grey="\033[90m"

info() {
    local text="$1"
    printf "$blue❯ $white$text"
}

upclear() {
    printf "\033[A" && printf "\r" && printf "\033[2K"
}

title() {
    clear
    echo -e "$purple"
    echo '    ____  ___________    _____       ______                         '
    echo '   / __ \/ ____/ ___/   / ___/____  / __/ /__      ______ _________ '
    echo '  / /_/ / /    \__ \    \__ \/ __ \/ /_/ __/ | /| / / __ `/ ___/ _ \'
    echo ' / ____/ /___ ___/ /   ___/ / /_/ / __/ /_ | |/ |/ / /_/ / /  /  __/'
    echo '/_/    \____//____/   /____/\____/_/  \__/ |__/|__/\__,_/_/   \___/ ©'
    echo ''
    echo -e "$white"
    printf "\t\t\tScript: $(basename $0)\n"
    echo ''
}

seek() {
    local variable=$1
    local prompt="$2"
    printf "$blue❯ $white$prompt: "
    read -p "" $variable
}

confirm() {
    while true; do
        printf "${blue}? ${white}Continue [Y/N]:\n"
        printf "${blue}❯ ${white}"
        read choice
        case "$choice" in
            [Yy] | [Yy][Ee][Ss] )
                upclear
                printf "${blue}❯ ${green}yes${white}\n"
                return 0 ;;
            [Nn] | [Nn][Oo] )
                upclear
                printf "${blue}❯ ${red}no${white}\n"
                return 1 ;;
            * )
                fail "Invalid"
                continue ;;
        esac
    done
}

warn() {
    printf "$yellow! ${@} !$white\n"
}

success() {
    printf "$green✓ $white${@}\n"
}

fail() {
    printf "$red✗ $white${@}\n"
}

spinner() {
    local pid=$1
    local delay=0.1
    local spinstr='|/-\'
    tput civis  # Hide cursor
    while [ "$(ps a | awk '{print $1}' | grep "$pid")" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    tput cnorm  # Show cursor
    printf "    \b\b\b\b"  # Clean up spinner
}

line() {
    echo -e "${purple}─────────────────────────────────────────────────────────────────${white}"
}
